"""create core learnloop tables

Revision ID: f3270c44f907
Revises: 
Create Date: 2026-09-22 14:26:04.099364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3270c44f907'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepts_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_concepts_subject'), ['subject'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=True),
    sa.Column('target_exam_date', sa.Date(), nullable=True),
    sa.Column('daily_study_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_prerequisites',
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_concept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('concept_id', 'prerequisite_concept_id')
    )
    with op.batch_alter_table('concept_prerequisites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concept_prerequisites_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concept_prerequisites_prerequisite_concept_id'), ['prerequisite_concept_id'], unique=False)

    op.create_table('masteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('mastery_score >= 0 AND mastery_score <= 1', name='ck_mastery_score_range'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'concept_id', name='uq_mastery_student_concept')
    )
    with op.batch_alter_table('masteries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_masteries_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_masteries_student_id'), ['student_id'], unique=False)

    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_documents_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_documents_subject'), ['subject'], unique=False)

    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_plans_student_id'), ['student_id'], unique=False)

    op.create_table('tutor_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tutor_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tutor_sessions_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tutor_sessions_student_id'), ['student_id'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_option', sa.String(length=255), nullable=False),
    sa.Column('misconception_tags', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('source_chunk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_source_chunk_id'), ['source_chunk_id'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.String(length=255), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_time_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempts_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_student_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_question_id'))

    op.drop_table('quiz_attempts')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_source_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_questions_concept_id'))

    op.drop_table('questions')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_concept_id'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('tutor_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tutor_sessions_student_id'))
        batch_op.drop_index(batch_op.f('ix_tutor_sessions_concept_id'))

    op.drop_table('tutor_sessions')
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_plans_student_id'))

    op.drop_table('study_plans')
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_documents_subject'))
        batch_op.drop_index(batch_op.f('ix_source_documents_student_id'))

    op.drop_table('source_documents')
    with op.batch_alter_table('masteries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_masteries_student_id'))
        batch_op.drop_index(batch_op.f('ix_masteries_concept_id'))

    op.drop_table('masteries')
    with op.batch_alter_table('concept_prerequisites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concept_prerequisites_prerequisite_concept_id'))
        batch_op.drop_index(batch_op.f('ix_concept_prerequisites_concept_id'))

    op.drop_table('concept_prerequisites')
    op.drop_table('students')
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepts_subject'))
        batch_op.drop_index(batch_op.f('ix_concepts_name'))

    op.drop_table('concepts')
    # ### end Alembic commands ###
